# Generated by Django 5.2.1 on 2025-05-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
