# Generated by Django 5.2.1 on 2025-05-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0002_produit_seuil_alerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_peremption',
            field=models.DateField(blank=True, null=True),
        ),
    ]
